CRUDwithoutEntity/Controllers/PatientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CRUDwithoutEntity.Models;
using System.Data.SqlClient;
using System.Configuration;
using System.Net;

namespace CRUDwithoutEntity.Controllers
{
    public class PatientController : Controller
    {
        // GET: Patient
        // 1. *************show the list of Patient in the Clinic ******************
       
        string constr = ConfigurationManager.ConnectionStrings["constr"].ConnectionString; 
        
        public ActionResult Index()
        {
            List<PatientModelVeiw> Patients = new List<PatientModelVeiw>();
            string query = "SELECT * FROM TblPatient";
            using (SqlConnection con = new SqlConnection(constr))
            {
                using (SqlCommand cmd = new SqlCommand(query))
                {
                    cmd.Connection = con;
                    con.Open();
                    using (SqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            Patients.Add(new PatientModelVeiw
                            {
                                Id = Convert.ToInt32(sdr["Id"]),
                                PatientName = Convert.ToString(sdr["PatientName"]),
                                PatientNumber = Convert.ToString(sdr["PatientNumber"]),
                                PatientEmail = Convert.ToString(sdr["PatientEmail"]),
                                Address = Convert.ToString(sdr["Address"]),
                                BloodGroup = Convert.ToString(sdr["BloodGroup"])
                            });
                        }
                    }
                    con.Close();
                }
            }

            if (Patients.Count == 0)
            {
                Patients.Add(new PatientModelVeiw());
            }
            return View(Patients);
        }


        // GET: Patient/PatientDetails/5
        public ActionResult PatientDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PatientModelVeiw Patient = new PatientModelVeiw();
            string query = "SELECT * FROM TblPatient where Id=" + id;
            using (SqlConnection con = new SqlConnection(constr))
            {
                using (SqlCommand cmd = new SqlCommand(query))
                {
                    cmd.Connection = con;
                    con.Open();
                    using (SqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            Patient = new PatientModelVeiw
                            {
                                Id = Convert.ToInt32(sdr["Id"]),
                                PatientName = Convert.ToString(sdr["PatientName"]),
                                PatientNumber = Convert.ToString(sdr["PatientNumber"]),
                                PatientEmail = Convert.ToString(sdr["PatientEmail"]),
                                Address = Convert.ToString(sdr["Address"]),
                                BloodGroup = Convert.ToString(sdr["BloodGroup"])
                            };
                        }
                    }
                    con.Close();
                }
            }
            if (Patient == null)
            {
                return HttpNotFound();
            }
            return View(Patient);
        }

        // 2. *************ADD NEW Patient in the Clinic ******************
        // GET: Home/CreatePatient
        public ActionResult CreatePatient()
        {
            return View();
        }

        // POST: Patient/CreatePatient
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreatePatient([Bind(Include = "Id,PatientName,PatientNumber,PatientEmail,Address,BloodGroup")] PatientModelVeiw patientModelVeiw)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (SqlConnection con = new SqlConnection(constr))
                    {
                        //inserting Patient data into database
                        string query = "insert into TblPatient values (@PatientName, @PatientNumber, @PatientEmail,@Address,@BloodGroup)";
                        using (SqlCommand cmd = new SqlCommand(query, con))
                        {
                            cmd.Connection = con;
                            cmd.Parameters.AddWithValue("@PatientName", patientModelVeiw.PatientName);
                            cmd.Parameters.AddWithValue("@PatientNumber", patientModelVeiw.PatientNumber);
                            cmd.Parameters.AddWithValue("@PatientEmail", patientModelVeiw.PatientEmail);
                           cmd.Parameters.AddWithValue("@Address", patientModelVeiw.Address);
                            cmd.Parameters.AddWithValue("@BloodGroup", patientModelVeiw.BloodGroup);
                            con.Open();
                            cmd.ExecuteNonQuery();
                            con.Close();
                        }
                    }
                    return RedirectToAction("Index");
                }
            }
            catch
            {
            }
            return View(patientModelVeiw);
        }

        // 3. *************Update Patient Detail in the Clinic ******************

        // GET: Patient/UpdatePatient/5
        public ActionResult UpdatePatient(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PatientModelVeiw Patient = new PatientModelVeiw();
            string query = "SELECT * FROM TblPatient where Id=" + id;
            using (SqlConnection con = new SqlConnection(constr))
            {
                using (SqlCommand cmd = new SqlCommand(query))
                {
                    cmd.Connection = con;
                    con.Open();
                    using (SqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            Patient = new PatientModelVeiw
                            {
                                Id = Convert.ToInt32(sdr["Id"]),
                                PatientName = Convert.ToString(sdr["PatientName"]),
                                PatientNumber = Convert.ToString(sdr["PatientNumber"]),
                                PatientEmail = Convert.ToString(sdr["PatientEmail"]),
                                Address = Convert.ToString(sdr["Address"]),
                                BloodGroup = Convert.ToString(sdr["BloodGroup"])
                            };
                        }
                    }
                    con.Close();
                }
            }
            if (Patient == null)
            {
                return HttpNotFound();
            }
            return View(Patient);
        }

        // POST: Patient/UpdatePatient/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdatePatient([Bind(Include = "Id,PatientName,PatientNumber,PatientEmail,Address,BloodGroup")] PatientModelVeiw patientModelVeiw)
        {
            if (ModelState.IsValid)
            {
                string query = "UPDATE TblPatient SET PatientName = @PatientName,PatientNumber=@PatientNumber, PatientEmail = @PatientEmail,Address=@Address,BloodGroup=@BloodGroup Where Id =@Id";
                using (SqlConnection con = new SqlConnection(constr))
                {
                    using (SqlCommand cmd = new SqlCommand(query))
                    {
                        cmd.Connection = con;
                        cmd.Parameters.AddWithValue("@PatientName", patientModelVeiw.PatientName);
                        cmd.Parameters.AddWithValue("@PatientNumber", patientModelVeiw.PatientNumber);
                        cmd.Parameters.AddWithValue("@PatientEmail", patientModelVeiw.PatientEmail);
                        cmd.Parameters.AddWithValue("@Address", patientModelVeiw.Address);
                        cmd.Parameters.AddWithValue("@BloodGroup", patientModelVeiw.BloodGroup);
                        cmd.Parameters.AddWithValue("@Id", patientModelVeiw.Id);
                        con.Open();
                        cmd.ExecuteNonQuery();
                        con.Close();
                    }
                }
                return RedirectToAction("Index");
            }
            return View(patientModelVeiw);
        }


        // 3. *************Deelete Patient in the Clinic ******************

        // GET: Patient/DeletePatient/5
        public ActionResult DeletePatient(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PatientModelVeiw Patient = new PatientModelVeiw();
            string query = "SELECT * FROM TblPatient where Id=" + id;
            using (SqlConnection con = new SqlConnection(constr))
            {
                using (SqlCommand cmd = new SqlCommand(query))
                {
                    cmd.Connection = con;
                    con.Open();
                    using (SqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            Patient = new PatientModelVeiw
                            {
                                Id = Convert.ToInt32(sdr["Id"]),
                                PatientName = Convert.ToString(sdr["PatientName"]),

CRUDwithoutEntity/Views/Patient/CreatePatient.cshtml
@model CRUDwithoutEntity.Models.PatientModelVeiw

@{
    ViewBag.Title = "CreatePatient";
}

<h2>CreatePatient</h2>
<br />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PatientName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PatientName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PatientName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PatientNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PatientNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PatientNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PatientEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PatientEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PatientEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BloodGroup, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BloodGroup, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BloodGroup, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index","Patient")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

CRUDwithoutEntity/Views/Patient/DeletePatient.cshtml
@model CRUDwithoutEntity.Models.PatientModelVeiw

@{
    ViewBag.Title = "DeletePatient";
}

<h2>Delete Patient</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PatientModelVeiw</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Patient Name")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PatientName)
        </dd>

        <dt>
            @Html.DisplayName("Patient Number")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PatientNumber)
        </dd>

        <dt>
            @Html.DisplayName("Patient Email")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PatientEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BloodGroup)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BloodGroup)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete Patient" class="btn btn-danger" /> 
            <br />
            <br />
            @Html.ActionLink("Back to List", "Index", "Patient")
        </div>
    }
</div>

CRUDwithoutEntity/Views/Patient/Index.cshtml
@model IEnumerable<CRUDwithoutEntity.Models.PatientModelVeiw>

@{
    ViewBag.Title = "Index";
}

<h2>Patients List</h2>
<br />
<p>
    @Html.ActionLink("Create New", "CreatePatient","Patient")
</p>
<br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Patient Name")
        </th>
        <th>
            @Html.DisplayName("Patient Number")
        </th>
        <th>
            @Html.DisplayName("Patient Email")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BloodGroup)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PatientName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PatientNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PatientEmail)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BloodGroup)
        </td>
        <td>
            @Html.ActionLink("Edit", "UpdatePatient", "Patient", new { id=item.Id }, null) |
            @Html.ActionLink("Show Details", "PatientDetails", "Patient", new { id=item.Id }, null) |
            @Html.ActionLink("Delete", "DeletePatient", "Patient", new { id=item.Id }, null)
        </td>
    </tr>
}

</table>

CRUDwithoutEntity/Views/Patient/PatientDetails.cshtml
@model CRUDwithoutEntity.Models.PatientModelVeiw

@{
    ViewBag.Title = "PatientDetails";
}

<h2>PatientDetails</h2>

<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
           @Html.DisplayName("Patient Name")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PatientName)
        </dd>

        <dt>
            @Html.DisplayName("Patient Number")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PatientNumber)
        </dd>

        <dt>
            @Html.DisplayName("Patient Email")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PatientEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BloodGroup)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BloodGroup)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "UpdatePatient","Patient", new { id = Model.Id },null) |
    @Html.ActionLink("Back to List", "Index","Patient")
</p>

CRUDwithoutEntity/Views/Patient/UpdatePatient.cshtml
@model CRUDwithoutEntity.Models.PatientModelVeiw

@{
    ViewBag.Title = "UpdatePatient";
}

<h2>Update Patient</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.Label("Patient Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PatientName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PatientName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Patient Number", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PatientNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PatientNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Patient Email", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PatientEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PatientEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BloodGroup, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BloodGroup, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BloodGroup, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index","Patient")
</div>